# Autogenerated wrapper script for libgpiod_jll for armv7l-linux-gnueabihf
export libgpiod

JLLWrappers.@generate_wrapper_header("libgpiod")
JLLWrappers.@declare_library_product(libgpiod, "libgpiod.so.3")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgpiod,
        "lib/libgpiod.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
